site_name: Vincent Vango

theme:
  icon:
    logo: material/van-utility
  name: material
  features:
    - header.autohide
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Light mode
      primary: blue
      accent: orange
  
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: orange

plugins: 
   - search :
   - resize-images:
        source-dir: assets-large
        target-dir: assets
        enable_cache: True
        size: [800, 600]
        extensions: ['.jpg', '.jpeg', '.png', '.gif', '.svg']

nav:
  - Home: 'index.md'
  - 'I. First Steps':
    - 'Bulkhead Removal': 'bulkhead-removal.md'
    - 'Rusty Floor': 'rusty-floor.md'
    - 'Stubby Antenna': 'stubby-antenna.md'
    - 'Missing Pieces': 'missing-pieces.md'
  - 'II. Insulation':
    - 'Headliner': 'headliner-insulation.md'
    - 'Sliding Door': 'slider-insulation.md'
    - 'Sidewall Insulation': 'sidewall-insulation.md'
  - 'III. Roof':
    - '80/20 Roof Rack': '8020-roof-rack.md'
    - 'Vent Fan': 'maxxfan.md'
  - 'IV. Electrical':
    - 'Solar Panels': 'solar-panels.md'
    - 'Powerbank': 'ecoflow.md'
    - 'Lighting': 'lighting.md'
  - 'V. Van Upgrades':
    - 'Tires': 'tires.md'
    - 'Radio': 'radio.md'
  - About: 'about.md'

    
markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  analytics:
    provider: google
    property: G-377BPYM659