site_name: Vincent Vango

theme:
  name: material
  icon:
    logo: assets/van-utility
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Light mode
      primary: blue
      accent: orange
  
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: orange

  plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true

plugins: 
   - search :
   - resize-images:
        source-dir: assets-large
        target-dir: assets
        enable_cache: True
        size: [800, 600]
        extensions: ['.jpg', '.jpeg', '.png', '.gif', '.svg']

nav:
  - Home: 'index.md'
  - 'I. First Steps':
    - 'Bulkhead Removal': 'bulkhead-removal.md'
    - 'Rusty Floor': 'rusty-floor.md'
    - 'Stubby Antenna': 'stubby-antenna.md'
  - 'II. Insulation':
    - 'Headliner': 'headliner-insulation.md'
    - 'Sliding Door': 'slider-insulation.md'
    - 'Sidewall Insulation': 'sidewall-insulation.md'
  - 'III. Roof':
    - '80/20 Roof Rack': '8020-roof-rack.md'
  - About: 'about.md'

    
markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg